### ISSUE TITLE
New favicon for the website

### ISSUE THREAD

**Issue by phbrasiliano** [FCCVienna/FCCVienna.github.io#24]
I would suggest adding a favicon to the website (the little icon that shows on browser's upper menu). Here are some suggestions:

- Austrian flag
- [Free Code Camp Symbol](https://avatars0.githubusercontent.com/u/9892522?v=4&s=400)
- Initials (like FCC or FCCV)

I could make the icon, but I would like to have some opinions on which colors we should use or which icon idea is the best.

**Comment by robaxelsen** [comment]
Hi @phbrasiliano! Thanks for posting the issue, and for volunteering to work on it :)

I personally like the one from the main freecodecamp.org website:
https://s3.amazonaws.com/freecodecamp/favicons/favicon.ico

..but I am also open to other ideas. Feel free to get creative :)

@DDCreationStudios @Otto-AA any ideas or opionions on this?

**Comment by Createdd** [comment]
I would vote for  **not**  having the freecodecamp favicon, because we have to be careful to not cause confusion. Our local group has to be obviously a LOCAL GROUP of freecodecamp. 
When we start to use more and more elements from the official site, we start to create confusion for our members and even regular FCC members. 
I even think this is one of the requirements for building local groups - to have a clear distinction. 

I would vote for the Austrian flag. But I am also open for everything. ;)

**Comment by Otto-AA** [comment]
Going with the freecodecamp-logo, you could try to add the Austria flag instead of the green background or the white logo.
But if that does not work out properly, I'd be fine with the normal freecodecamp favicon aswell =D


________________________________
Von: Robert Axelsen <notifications@github.com>
Gesendet: Montag, 28. August 2017 15:34
An: FCCVienna/FCCVienna.github.io
Cc: A_A; Mention
Betreff: Re: [FCCVienna/FCCVienna.github.io] New favicon for the website (#24)


Hi @phbrasiliano<https://github.com/phbrasiliano>! Thanks for posting the issue, and for volunteering to work on it :)

I personally like the one from the main freecodecamp.org website:
https://s3.amazonaws.com/freecodecamp/favicons/favicon.ico

..but I am also open to other ideas. Feel free to get creative :)

@DDCreationStudios<https://github.com/ddcreationstudios> @Otto-AA<https://github.com/otto-aa> any ideas or opionions on this?

**Comment by robaxelsen** [comment]
@DDCreationStudios @Otto-AA Great suggestions and points, both of you. I think we should focus on a first iteration with the Austrian flag then, and see how it looks. Ok, @phbrasiliano?

**Comment by phbrasiliano** [comment]
Here are some icons I made (and left the youtube favicon for comparison), I'm no designer but I think the first (red flame with Austrian flag) looks decent. If you guys prefer I could just use the flag as @DDCreationStudios suggested. 

![untitled-3](https://user-images.githubusercontent.com/19431410/29794421-94cabdcc-8c50-11e7-82da-77cb2aa9ba14.png)

I made some other experimentations with the Free Code Camp logo, but the results were not that good on the small icon.
If there are no objections I can upload the changes tomorrow morning.

**Comment by Otto-AA** [comment]
The first one is my favourite aswell 😄 

What do you think @DDCreationStudios @robeerob ?

**Comment by robaxelsen** [comment]
@phbrasiliano Well done! :+1: :tada: I also like the combination of flag and flame in the first one, but could you make another variation with white inside flame, instead of dark red? Think I will look "cleaner" then, and closer to FCC logo.

**Comment by phbrasiliano** [comment]
![frog](https://user-images.githubusercontent.com/19431410/29810791-ecfa1390-8ca9-11e7-923b-0795c6789158.png)

![favicon-13](https://user-images.githubusercontent.com/19431410/29810800-f57c45e2-8ca9-11e7-94b5-1ada07d094a6.png)

I followed the @robeerob suggestion and I think the result is pretty good. I'll leave it here for a while and soon upload the icon.

**Comment by Createdd** [comment]
@phbrasiliano  Wow this looks really cool!
